site_name: SeaTable 脚本编程手册
site_author: seatable
docs_dir: ./manual
site_url: https://seatable.github.io/seatable-scripts-cn/


repo_name: seatable/seatable-scripts-cn
repo_url: https://github.com/seatable/seatable-scripts-cn/

copyright: Copyright &copy; 2020 seatable

theme:
  name: material
  # icon:
  logo: assets/logo32_32.png
  favicon: assets/seatable-favicon.ico
  # features:
    # - tabs
  palette:
    primary: deep orange
    accent:

plugins:
  - search # necessary for search to work
  - awesome-pages

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seatable/seatable-scripts-cn/

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "1-4"


# Page tree
nav:
  - 引言: README.md
  - 对象数据结构: data-structure.md
  - Base: base.md
  - Output: output.md
  - Utils: utils.md